In [2]:
import pandas as pd
import numpy as np
import random
df = pd.read_csv('WA_Fn-UseC_-IT-Help-Desk.csv',delimiter=',')
df

,ticket,requestor,RequestorSeniority,ITOwner,FiledAgainst,TicketType,Severity,Priority,daysOpen,Satisfaction
0,1,1929,1 - Junior,50,Systems,Issue,2 - Normal,0 - Unassigned,3,1 - Unsatisfied
1,2,1587,2 - Regular,15,Software,Request,1 - Minor,1 - Low,5,1 - Unsatisfied
2,3,925,2 - Regular,15,Access/Login,Request,2 - Normal,0 - Unassigned,0,0 - Unknown
3,4,413,4 - Management,22,Systems,Request,2 - Normal,0 - Unassigned,20,0 - Unknown
4,5,318,1 - Junior,22,Access/Login,Request,2 - Normal,1 - Low,1,1 - Unsatisfied
...,...,...,...,...,...,...,...,...,...,...
99995,99996,1999,2 - Regular,50,Systems,Issue,2 - Normal,1 - Low,4,1 - Unsatisfied
99996,99997,932,4 - Management,8,Access/Login,Request,2 - Normal,2 - Medium,0,0 - Unknown
99997,99998,213,1 - Junior,47,Access/Login,Issue,1 - Minor,0 - Unassigned,0,1 - Unsatisfied
99998,99999,1069,2 - Regular,32,Systems,Request,2 - Normal,0 - Unassigned,16,3 - Highly satisfied
99999,100000,1095,2 - Regular,20,Systems,Issue,2 - Normal,1 - Low,6,2 - Satisfied

In [33]:
tipo_incidencia = ['Falta de suministro de gas.',
'Lectura incorrecta del medidor.',
'Fugas de gas.',
'Problemas con la facturación.',
'Cambio de titularidad.',
'Modificación de contrato.',
'Reparación de averías en la instalación de gas.',
'Solicitar una inspección de seguridad.',
'Solicitar un aumento o disminución de la potencia contratada.',
'Problemas con el acceso al contador.',
'Consultas sobre consumos anormales.',
'Consultas sobre tarifas y opciones de contratación.',
'Reclamaciones sobre el servicio de atención al cliente.',
'Informar sobre cambios de dirección.',
'Solicitar una revisión o calibración del medidor.',
'Consultas sobre lecturas estimadas.',
'Problemas con la lectura a distancia del medidor.',
'Consultas sobre el plan de mantenimiento de la instalación.',
'Informar sobre olores extraños o sospechas de fugas de gas.',
'Consultas sobre el cumplimiento de normativas y regulaciones.'
]

In [37]:
provincias=["Álava", "Albacete", "Alicante", "Almería", "Asturias", "Ávila", "Badajoz", "Barcelona", "Burgos", "Cáceres", "Cádiz", "Cantabria", "Castellón", "Ciudad Real", "Córdoba", "Cuenca", "Girona", "Granada", "Guadalajara", "Guipúzcoa", "Huelva", "Huesca", "Islas Baleares", "Jaén", "La Coruña", "La Rioja", "Las Palmas", "León", "Lleida", "Lugo", "Madrid", "Málaga", "Murcia", "Navarra", "Orense", "Palencia", "Pontevedra", "Salamanca", "Santa Cruz de Tenerife", "Segovia", "Sevilla", "Soria", "Tarragona", "Teruel", "Toledo", "Valencia", "Valladolid", "Vizcaya", "Zamora", "Zaragoza"];

In [55]:
dic_ciudades = {
    'Álava': [
        ('Vitoria-Gasteiz', '01001'),
        ('Amurrio', '01470'),
        ('Llodio', '01400')
    ],
    'Albacete': [
        ('Albacete', '02001'),
        ('Hellín', '02400'),
        ('Villarrobledo', '02600')
    ],
    'Alicante': [
        ('Alicante', '03001'),
        ('Elche', '03201'),
        ('Torrevieja', '03180')
    ],
    'Almería': [
        ('Almería', '04001'),
        ('Roquetas de Mar', '04740'),
        ('El Ejido', '04700')
    ],
    'Asturias': [
        ('Oviedo', '33001'),
        ('Gijón', '33201'),
        ('Avilés', '33401')
    ],
    'Ávila': [
        ('Ávila', '05001'),
        ('Arévalo', '05200'),
        ('El Tiemblo', '05270')
    ],
    'Badajoz': [
        ('Badajoz', '06001'),
        ('Mérida', '06800'),
        ('Almendralejo', '06200')
    ],
    'Barcelona': [
        ('Barcelona', '08001'),
        ('Badalona', '08911'),
        ('Hospitalet de Llobregat', '08901')
    ],
    'Burgos': [
        ('Burgos', '09001'),
        ('Miranda de Ebro', '09200'),
        ('Aranda de Duero', '09400')
    ],
    'Cáceres': [
        ('Cáceres', '10001'),
        ('Plasencia', '10600'),
        ('Trujillo', '10200')
    ],
    'Cádiz': [
        ('Cádiz', '11001'),
        ('Jerez de la Frontera', '11401'),
        ('Algeciras', '11201')
    ],
    'Cantabria': [
        ('Santander', '39001'),
        ('Torrelavega', '39300'),
        ('Camargo', '39600')
    ],
    'Castellón': [
        ('Castellón de la Plana', '12001'),
        ('Villarreal', '12540'),
        ('Burriana', '12530')
    ],
    'Ciudad Real': [
        ('Ciudad Real', '13001'),
        ('Puertollano', '13500'),
        ('Tomelloso', '13700')
    ],
    'Córdoba': [
        ('Córdoba', '14001'),
        ('Lucena', '14900'),
        ('Puente Genil', '14500')
    ],
    'Cuenca': [
        ('Cuenca', '16001'),
        ('Tarancón', '16400'),
        ('Motilla del Palancar', '16200')
    ],
    'Girona': [
        ('Girona', '17001'),
        ('Figueres', '17600'),
        ('Blanes', '17300')
    ],
    'Granada': [
        ('Granada', '18001'),
        ('Motril', '18600'),
        ('Almuñécar', '18690')
    ],
    'Guadalajara': [
        ('Guadalajara', '19001'),
        ('Azkoitia', '20001'),
        ('Alcalá de Henares', '28801')
    ],
    'Guipúzcoa': [
        ('San Sebastián', '20001'),
        ('Irún', '20301'),
        ('Éibar', '20600')
    ],
    'Huelva': [
        ('Huelva', '21001'),
        ('Isla Cristina', '21410'),
        ('Punta Umbría', '21100')
    ],
    'Huesca': [
        ('Huesca', '22001'),
        ('Barbastro', '22300'),
        ('Monzón', '22400')
    ],
    'Islas Baleares': [
        ('Palma de Mallorca', '07001'),
        ('Ibiza', '07800'),
        ('Manacor', '07500')
    ],
    'Jaén': [
        ('Jaén', '23001'),
        ('Linares', '23700'),
        ('Andújar', '23740')
    ],
    'La Coruña': [
        ('La Coruña', '15001'),
        ('Santiago de Compostela', '15701'),
        ('Ferrol', '15401')
    ],
    'La Rioja': [
        ('Logroño', '26001'),
        ('Calahorra', '26500'),
        ('Arnedo', '26580')
    ],
    'Las Palmas': [
        ('Las Palmas de Gran Canaria', '35001'),
        ('Telde', '35200'),
        ('Santa Lucía', '35110')
    ],
    'León': [
        ('León', '24001'),
        ('Ponferrada', '24400'),
        ('San Andrés del Rabanedo', '24191')
    ],
    'Lleida': [
        ('Lleida', '25001'),
        ('Balaguer', '25300'),
        ('Mollerussa', '25230')
    ],
    'Lugo': [
        ('Lugo', '27001'),
        ('Villalba', '27800'),
        ('Sarria', '27600')
    ],
    'Madrid': [
        ('Madrid', '28001'),
        ('Móstoles', '28931'),
        ('Alcalá de Henares', '28801')
    ],
    'Málaga': [
        ('Málaga', '29001'),
        ('Marbella', '29600'),
        ('Vélez-Málaga', '29700')
    ],
    'Murcia': [
        ('Murcia', '30001'),
        ('Cartagena', '30201'),
        ('Lorca', '30800')
    ],
    'Navarra': [
        ('Pamplona', '31001'),
        ('Tudela', '31500'),
        ('Barañáin', '31010')
    ],
    'Orense': [
        ('Orense', '32001'),
        ('Pontevedra', '36001'),
        ('Lugo', '27001')
    ],
    'Palencia': [
        ('Palencia', '34001'),
        ('Aguilar de Campoo', '34800'),
        ('Dueñas', '34110')
    ],
    'Pontevedra': [
        ('Vigo', '36201'),
        ('Pontevedra', '36001'),
        ('Vilagarcía de Arousa','36600')
    ],
    'Salamanca': [
        ('Salamanca', '37001'),
        ('Béjar', '37700'),
        ('Ciudad Rodrigo', '37500')
    ],
    'Segovia': [
        ('Segovia', '40001'),
        ('Cuéllar', '40200'),
        ('Cantalejo', '40320')
    ],
    'Sevilla': [
        ('Sevilla', '41001'),
        ('Dos Hermanas', '41701'),
        ('Alcalá de Guadaíra', '41500')
    ],
    'Soria': [
        ('Soria', '42001'),
        ('Almazán', '42200'),
        ('Ólvega', '42110')
    ],
    'Tarragona': [
        ('Tarragona', '43001'),
        ('Reus', '43201'),
        ('El Vendrell', '43700')
    ],
    'Santa Cruz de Tenerife': [
        ('Santa Cruz de Tenerife', '38001'),
        ('San Cristóbal de La Laguna', '38201'),
        ('Arona', '38650')
    ],
    'Teruel': [
        ('Teruel', '44001'),
        ('Alcañiz', '44600'),
        ('Calamocha', '44200')
    ],
    'Toledo': [
        ('Toledo', '45001'),
        ('Talavera de la Reina', '45600'),
        ('Illescas', '45200')
    ],
    'Valencia': [
        ('Valencia', '46001'),
        ('Sagunto', '46500'),
        ('Gandía', '46700')
    ],
    'Valladolid': [
        ('Valladolid', '47001'),
        ('Medina del Campo', '47400'),
        ('Laguna de Duero', '47140')
    ],
    'Vizcaya': [
        ('Bilbao', '48001'),
        ('Barakaldo', '48901'),
        ('Getxo', '48991')
    ],
    'Zamora': [
        ('Zamora', '49001'),
        ('Benavente', '49600'),
        ('Toro', '49800')
    ],
    'Zaragoza': [
        ('Zaragoza', '50001'),
        ('Calatayud', '50300'),
        ('Utebo', '50180')
    ]
}

In [71]:
distribuidores = [
    'UFD',
    'Naturgy'
]

In [84]:
col = ['numero_abonado','dia','tipos_incidencia','inicio_servicio','fin_servicio','urgente','nivel_prioridad','grado_satisfación','provincia','ciudad','codigo_postal','origen_cliente','distribuidor']
df_new = pd.DataFrame(columns=col)
df_new['numero_abonado'] = df['requestor']
df_new['tipos_incidencia'] = [tipo_incidencia[random.randint(0,len(tipo_incidencia)-1)] for x in df['Satisfaction']]
df_new['inicio_servicio'] = [str(random.randint(1,15))+ ' Juny' for x in df_new['dia']]
df_new['dia'] = [str(int(x.split(' ')[0])-1) + ' Juny' if int(x.split(' ')[0])-1 > 1 else str(int(x.split(' ')[0])-1 + 31) + ' May' for x in df_new['inicio_servicio']]
df_new['fin_servicio'] = [str(int(df_new['inicio_servicio'][x].split(' ')[0])+int(df['daysOpen'][x]))+' Juny' if int(int(df_new['inicio_servicio'][x].split(' ')[0])+int(df['daysOpen'][x])) < 31 else str(int(df_new['inicio_servicio'][x].split(' ')[0])+int(df['daysOpen'][x]) -30)+' July' for x in range(len(df_new['inicio_servicio']))]

df_new['urgente'] = [x[0] for x in df['Severity']]
df_new['nivel_prioridad'] = [x for x in df['Priority']]
df_new['grado_satisfación'] = [x[0] for x in df['Satisfaction']]
df_new['provincia'] = [provincias[random.randint(1,len(provincias)-1)] for x in df_new['grado_satisfación']]
ciutats  = [dic_ciudades[x][random.randint(0,len(dic_ciudades[x])-1)] for x in df_new['provincia']]
df_new['ciudad'] = [x[0] for x in ciutats]
df_new['codigo_postal'] = [x[1] for x in ciutats]
df_new['origen_cliente'] = [x for x in df_new['ciudad']]
df_new['distribuidor'] = [distribuidores[random.randint(0,len(distribuidores)-1)] for x in df_new['numero_abonado']]

In [85]:
df_new

,numero_abonado,dia,tipos_incidencia,inicio_servicio,fin_servicio,urgente,nivel_prioridad,grado_satisfación,provincia,ciudad,codigo_postal,origen_cliente,distribuidor
0,1929,3 Juny,Informar sobre cambios de dirección.,4 Juny,7 Juny,2,0 - Unassigned,1,Pontevedra,Vigo,36201,Vigo,UFD
1,1587,13 Juny,Consultas sobre lecturas estimadas.,14 Juny,19 Juny,1,1 - Low,1,Toledo,Illescas,45200,Illescas,Naturgy
2,925,7 Juny,Modificación de contrato.,8 Juny,8 Juny,2,0 - Unassigned,0,Cáceres,Trujillo,10200,Trujillo,UFD
3,413,8 Juny,Consultas sobre el cumplimiento de normativas ...,9 Juny,29 Juny,2,0 - Unassigned,0,Orense,Pontevedra,36001,Pontevedra,Naturgy
4,318,11 Juny,Reparación de averías en la instalación de gas.,12 Juny,13 Juny,2,1 - Low,1,Huelva,Isla Cristina,21410,Isla Cristina,UFD
...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,1999,2 Juny,Solicitar un aumento o disminución de la poten...,3 Juny,7 Juny,2,1 - Low,1,Lleida,Balaguer,25300,Balaguer,Naturgy
99996,932,6 Juny,Fugas de gas.,7 Juny,7 Juny,2,2 - Medium,0,Toledo,Talavera de la Reina,45600,Talavera de la Reina,Naturgy
99997,213,13 Juny,Informar sobre cambios de dirección.,14 Juny,14 Juny,1,0 - Unassigned,1,Girona,Blanes,17300,Blanes,Naturgy
99998,1069,6 Juny,Consultas sobre consumos anormales.,7 Juny,23 Juny,2,0 - Unassigned,3,Lugo,Villalba,27800,Villalba,UFD
99999,1095,10 Juny,Falta de suministro de gas.,11 Juny,17 Juny,2,1 - Low,2,Orense,Pontevedra,36001,Pontevedra,UFD